### ISSUE TITLE
Is extension published on Safari Extensions same thing as this repo?

### ISSUE THREAD

**Issue by pkuczynski** [el1t/uBlock-Safari#52]
I found this extension: https://safari-extensions.apple.com/details/?id=com.el1t.uBlock-8782JU4WM4

Is this the same thing as your work?

**Comment by ruchernchong** [comment]
Apparently, it is. See #34

**Comment by cenon415** [comment]
UnsubscribeOn Jun 12, 2017 5:25 PM, Chong Ru Chern <notifications@github.com> wrote:Apparently, it is. See #34

**Comment by pkuczynski** [comment]
Only partially, as the Safari Extensions serve a much older version that the once which can be found here: https://github.com/el1t/uBlock-Safari/releases

**Comment by el1t** [comment]
Actually, it is not quite—it was uploaded by another person signed with their own certificate. The two versions therefore cannot be installed on top of each other. That should change whenever Apple decides to process my submission.

Edit: deleted comment that read "unsubscribe"

**Comment by wkoncki** [comment]
@el1t Can you please drop us an update in this thread when your extensions goes through review and appears in the store?

**Comment by Revod** [comment]
I want to know if the store version is the latest? I can't install extensions outside of the store (idk the reason because before I was able to do) so I successfully Installed the store version but said uBlock Origin v1.11.3.1

**Comment by Baccount** [comment]
The ublock extention in the store is not a officially released by el1t.
Install the latest version from el1t github page, after you download open Safari preferences then open the extension page and drag the latest ublock extention file onto it.

**Comment by Revod** [comment]
I tried different way, all the ways possible and one day I simply can't install any extension :/

**Comment by ServerWrestler** [comment]
I was able to clone and build successfully.  Version 1.12.5.100 on latest stable macOS and Safari.  The version listed on the Apple Safari Extension page is a little old as mentioned.  This is a bit difficult for the average user though.

Since @el1t is going to update issue #34 when Apple let's him update their page maybe this issue can be closed?

**Comment by ServerWrestler** [comment]
@Revod you can go to https://github.com/el1t/uBlock-Safari/releases and download the latest uBlock0.safariextz.  Then open Safari => Preferences => Extensions and drag the uBlock0.safariextz file into the Extensions pane.  It will ask if you want to trust the extension.  Say yes.  You should be good to go.  I just tested and this works.

**Comment by mrdc** [comment]
@the-sillystring Unfortunately, it's not working for me - nothing happens when I press Trust button.

**Comment by Baccount** [comment]
@mrdc  Open Safari preferences and go to the advanced tab,  check show developer menu/panel. In the menu bar click on the developer button in in the list click on allow unsigned/untrusted extensions.  Delete any extension that is named ublock,  but make sure you back up any list/rules first. And then drag the latest ublock origin release  that you get from https://github.com/el1t/uBlock-Safari/releases onto the extensions panel in Safari.  And when it ask you to trust it click on trust that should fix the issue.

**Comment by mrdc** [comment]
@Baccount Allow Unsigned Extensions is enabled - still can't install - nothing happens after I press Trust.

**Comment by el1t** [comment]
@mrdc please see [troubleshooting](https://github.com/el1t/uBlock-Safari/tree/safari/dist/README.md#troubleshooting)

Edit: this also isn't the best place to raise install issues; first search for previously opened issues (#6, #29) and if those don't work, open a new one. Thanks.

**Comment by vassudanagunta** [comment]
It appears that the unauthorized publish of uBlock Origin to the Extensions Gallery by @hartator  has been pulled.  It no longer comes up on search (https://safari-extensions.apple.com/?q=ublock).

@el1t maybe you can publish the latest release now (and close this issue)?

**Comment by vassudanagunta** [comment]
I was wrong. The unauthorized and unverified binary put up on the Extensions Gallery by @hartator is still up.  I created Issue #69 to track and discuss.

**Comment by vassudanagunta** [comment]
To help out the maintainer, @el1t, can we close this issue? The question has been answered, and we are tracking the unauthorized extension and website via #69. Ellis is working on submitting an update to the App Store (which has replaced the Extension Gallery).
